export const cardsData = [
  {
    id: "core",
    icon: "https://resourceinn.com/wp-content/uploads/2024/04/core-hr.svg",
    title: "Core HR",
    description: "For managing the basic HR operations",
    subDescription: "Make your record management easier than ever before",
    useCases: [
      	

"People Record Management",
 "Custom Dashboard",
  "Organogram",
 "Employee Self-service (ESS)",
"People Assets",
"Report Scheduler",
    ],
    getStartedLink: "https://resourceinn.com/free-trial-core/",
    learnMoreLink: "https://resourceinn.com/core-hr-software/",
    className: "bg-white hover:shadow-purple-500",
     buttonColor: "purple",
  },
  {
    id: "attendance",
    icon: "https://resourceinn.com/wp-content/uploads/2024/04/attendance.svg",
    title: "Attendance & Leave",
    description: "For people time tracking & leave management",
    subDescription: "Keep your SOPs transparent with people’s satisfaction",
    useCases: [
      "Roster & Time Scheduling",
"Leave Management",
"Biometric Integrations",
"Travel & Official Duties",
"Geofencing ",
    ],
    getStartedLink: "https://resourceinn.com/free-trial-attendance/",
    learnMoreLink: "https://resourceinn.com/attendance-software/",
    className: "bg-white hover:shadow-orange-600",
     buttonColor: "orange",
  },
  {
    id: "payroll",
    icon: "https://resourceinn.com/wp-content/uploads/2024/04/payroll.svg",
    title: "Payroll",
    description: "For managing your people’s payroll operations easily",
    subDescription: "Save your time with fast, easy & accurate payroll",
    useCases: [
"Tax & Compliance",
"Pay Slips",
"Integrations",
"Compensations",
"Custom Pay Items",
"Leave Encashment",
"Final Settlement ",
      
    ],
    getStartedLink: "https://resourceinn.com/free-trial-payroll/",
    learnMoreLink: "https://resourceinn.com/payroll-software/",
    className: "bg-white hover:shadow-green-500",
     buttonColor: "green",
  },
  {
    id: "performance",
    icon: "https://resourceinn.com/wp-content/uploads/2024/04/performance.svg",
    title: "Performance",
    description: "For effective people monitoring & evaluations",
    subDescription: "Monitor, analyze & track goals in the right direction",
    useCases: [
"    360 Feedback",
    "Qualitative",
    "OKR",
    "Appraisals",
    "Analysis",
    "Objective Setting",
    "Self Evaluation",


    ],
    getStartedLink: "https://resourceinn.com/free-trial-performance/",
    learnMoreLink: "https://resourceinn.com/performance-software/",
    className: "bg-white hover:shadow-blue-500",
     buttonColor: "blue",
  },
  {
    id: "recruitment",
    icon: "https://resourceinn.com/wp-content/uploads/2024/04/recruitment.svg",
    title: "Recruitment",
    description: "For effective hiring & onboarding procedures",
    subDescription: "Hire the right talent for the right positions",
    useCases: [
      "Applicant Tracking System (ATS)",
      "Onboarding",
      "Notification & Alerts",
      "Evaluation",
      "CV Bank",
      "Recruitment Funnel",
    ],
    getStartedLink: "https://resourceinn.com/free-trial-recruitment/",
    learnMoreLink: "https://resourceinn.com/cloud-based-recruiting-software/",
    className: "bg-white hover:shadow-orange-300",
     buttonColor: "orange",
  },
  {
    id: "training",
    icon: "https://resourceinn.com/wp-content/uploads/2024/04/training.svg",
    title: "Training & Development",
    description: "Fill the learning gaps of your workforce with proper training",
    subDescription: "Make your people stay on top of fast-paced competitions",
    useCases: [
      "Course Planning",
      "Media Library Course Material",
      "Scheduling of Training Events",
      "Training Calendar",
      "Certificate",
    ],
    getStartedLink: "https://resourceinn.com/free-trial-td",
    learnMoreLink: "https://resourceinn.com/employee-training-and-development-software/",
    className: "bg-white hover:shadow-sky-300",
     buttonColor: "blue",
  },
];
