
export const Widthdata = [
  {
    id: "Options",
    image: "https://resourceinn.com/wp-content/uploads/2024/04/attendance-tracking.webp",
    title: "Multiple Attendance Options",
    subtitle: "For managing the basic HR operations",
    description: "Track your people’s overtime and work hours easily through our state-of-the-art attendance module that allows different ways to ensure presence.",
    useCases: [
      	
"GPS-based attendance system for off-site workers",
"Connect with multiple attendance devices",
"Mark attendance through multiple options i.e RFID, Biometric, mobile & desktop ",
"People Record Management",
    ],
    buttonname:"Explore Hardware Integrations →",
    buttonlink:"https://resourceinn.com/hr-software-integrations/",
    className: "bg-white hover:shadow-purple-500",
     buttonColor: "purple",
  },
  {
    id: "progress",
    image: "https://resourceinn.com/wp-content/uploads/2024/04/company-culture.webp",
    title: "Progressive Culture Building",
    subtitle: "Build a Better Employee Experience",
    description: "Track your people’s overtime and work hours easily through our state-of-the-art attendance module that allows different ways to ensure presence.",
    useCases: [
        "Interactive performance management system",
"Employee career development",
"Efficient training & development",
"Engage your people through Mobile App",
"Employee Engagement with birthday, accolades & more",
"Flexible policy implementation ",
    ],
    buttonname :"Explore Employee Engagement →",
    buttonlink: "https://resourceinn.com/employee-engagement",
    className: "bg-white hover:shadow-orange-600",
     buttonColor: "orange",
  },
  {
    id: "Tools",
    image: "https://resourceinn.com/wp-content/uploads/2024/08/integration-01.webp",
    title: "Seamless Integration with the Popular Tools",
    Subtitle: "Prepare Your Organization for any Eventuality",
    description: "Resourceinn HRMS supports HRs to connect with the tools they want and make the work easy even more.",
   buttonname: "Explore All Integrations →",
    buttonlink: "https://resourceinn.com/integrations/",
    className: "bg-white hover:shadow-green-500",
     buttonColor: "green",
  },
  {
    id: "reports",
    icon: "https://resourceinn.com/wp-content/uploads/2024/01/reports-analytics-dashboard-1024x675.webp",
    title: "Reduce Threats with Reports Based on Historical Analysis",
    subtitle: "Powerful Insights that Keep You a Step Ahead",
    description:"Resourceinn a smart hr management software provides brief and insightful reports on the metrics that matter. You can make customizable reports and business letters as per your requirements too.",
    buttonname: "Discover HR Reporting →",
    buttonlink: "https://resourceinn.com/hr-reporting-software/",
    className: "bg-white hover:shadow-blue-500",
     buttonColor: "blue",
  },
  {
    id: "controls",
    image: "https://resourceinn.com/wp-content/uploads/2024/08/secure-data.webp",
    title: "Data Security with Visibility Controls the Way you Want",
    subtitle: "Maintain Confidentiality within Your Organization",
    description: "Our data visibility control system lets you decide what sensitive data you want to show or hide from people based on your hierarchical structure. You can also build custom access cycles if required.",
    buttonname: "Customize Access Controls →",
    buttonlink: "https://resourceinn.com/core-hr-software#access-control",
    className: "bg-white hover:shadow-orange-300",
     buttonColor: "orange",
  },
  {
    id: "connected",
    image: "https://resourceinn.com/wp-content/uploads/2024/04/mobile-screens.webp",
    title: "Stay Connected with ourSmart Mobile App",
    description: "Mark your attendance with a single tap. Get notifications. A smart app that allows you to process requests instantly & stay updated about your staff location through GEO fencing or via a Mobile app.",
    useCases: [
        "Attendance with GEO location",
"Productivity driven time Sheets",
"Process requests & approvals",
"Get updated with notifications",
    ],
    buttonname: "Resourceinn Mobile App →",
    buttonlink: "https://resourceinn.com/location-based-attendance-mobile-app/",
    className: "bg-white hover:shadow-sky-300",
     buttonColor: "blue",
  },
];