import type { Metadata } from "next";
import Navbar from "@/app/(forntend)/components/Navbar";
import Footer from "@/app/(forntend)/components/footer";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import connectdatabase from "@/app/(backend)/lib/db"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await connectdatabase(); 

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
